# Generated by Django 3.1.3 on 2020-12-02 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='ObjB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='ObjC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('relA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objcs', to='issue_77.obja')),
                ('relB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objcs', to='issue_77.objb')),
            ],
        ),
    ]
