# Generated by Django 4.2.5 on 2023-11-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffee", "0006_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="flavor",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
