# Generated by Django 3.1.7 on 2021-03-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('is_completed', models.BooleanField(blank=True, default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
