name: 📑 Docs
description: Propose changes and improvements to Django Unicorn Docs.
labels: "📑 docs"
title: "[📑 Docs]: "

body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to Django Unicorn! 📑 👩🏻‍💻 We appreciate your feedback, ideas, and contributions. 
        
        Before filing this issue, please make sure to check if there's already a similar issue opened.
  
  - type: textarea
    id: reason-context
    attributes:
      label: What Dev Docs changes are you proposing?
      description: Why do the Docs need this improvement? What is the motivation for this change?
      placeholder: "I would like to contribute to Django Unicorn 📑 by..."
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/adamghill/django-unicorn/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true