# Generated by Django 3.1.7 on 2021-04-23 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=1024)),
                ('board_revision', models.FloatField(default=1)),
                ('board_variant', models.CharField(default='A', max_length=5)),
                ('board_added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('board_last_edited_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('board_last_component_upload_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('board_value_update_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('board_appears_on_tania', models.BooleanField(default=False)),
                ('board_added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_board_added_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
            },
        ),
        migrations.CreateModel(
            name='Board_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=1024)),
                ('badge_class', models.CharField(blank=True, default='primary', max_length=45, null=True)),
                ('custom_color', models.CharField(blank=True, max_length=45, null=True)),
                ('force_custom_color', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Board Status',
                'verbose_name_plural': 'Board Statuses',
            },
        ),
        migrations.CreateModel(
            name='Board_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bi_image', models.ImageField(blank=True, null=True, upload_to='uploads/board-images/%Y/%m/%d/')),
                ('bi_upload_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('bi_board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='electronics.board')),
            ],
            options={
                'verbose_name': 'Board Image',
                'verbose_name_plural': 'Board Images',
            },
        ),
        migrations.CreateModel(
            name='Board_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='electronics.board_category')),
            ],
            options={
                'verbose_name': 'Board Category',
                'verbose_name_plural': 'Board Categories',
            },
        ),
        migrations.AddField(
            model_name='board',
            name='board_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='electronics.board_category'),
        ),
        migrations.AddField(
            model_name='board',
            name='board_cover_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='electronics.board_image'),
        ),
        migrations.AddField(
            model_name='board',
            name='board_group_visibility',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='board',
            name='board_last_component_upload_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_board_last_component_upload_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='board_last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_board_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='board_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='electronics.board_status'),
        ),
    ]
